### ISSUE TITLE
Bug in the sample_by_column Function

### ISSUE THREAD

**Issue by brichard1638** [oobianom/quickcode#1]
The **sample_by_column** function does not return the correct number of records consistent with its n argument.

To reproduce this error, execute the following code via iteration:
`library(quickcode)`
`data("airquality")`
`nrow(sample_by_column(.dt = airquality, col = Ozone, n = 12))`
[1] 15
`nrow(sample_by_column(.dt = airquality, col = Ozone, n = 12))`
[1] 22
`nrow(sample_by_column(.dt = airquality, col = Ozone, n = 12))`
[1] 19
`nrow(sample_by_column(.dt = airquality, col = Ozone, n = 12))`
[1] 19

**Comment by oobianom** [comment]
Thanks for bring this issue up. I will work to address it soonest.

**Comment by oobianom** [comment]
Addressed!
