### ISSUE TITLE
Extend Functionality of the is.image Function

### ISSUE THREAD

**Issue by brichard1638** [oobianom/quickcode#11]
Currently, the **is.image** function can only process a single passed file name element, returning a scaler. It is recommended that the functionality of the **is.image** function be extended to allow a vector of file names to be processed.

An implementation example of this extended functionality is provided below:
`v = c("logo.png", "business process.pdf", "front_cover.jpg", "intro.docx", "financial_future.doc", "2022 buybacks.xlsx")`
`output = is.image(v)`

output
[1] TRUE  FALSE  TRUE  FALSE  FALSE  FALSE

**Comment by oobianom** [comment]
Hi Brice, I updated the code for this. Take a look when you have some time.

**Comment by brichard1638** [comment]
I tested the **is.image** function and it passed. The only thing I would consider changing is to add more image-based file types to the function. Not to be excessive about the details, it is recommended that the following image file extensions be added for no other reason than to address legacy-based image file extensions that may still be actively used today:

- cdr - Corel Draw Picture
- cgm - Computer Graphic File
- cur - Windows Cursor
- fpx - FlashPix
- img - GEM Image File
- mac - MacPaint
- pcd - Kodak PhotoCD
- pcx - Zsoft PC Paintbrush
- wmf - Placeable Metafile
- wpg - DrawPerfect

NOTE: It is important to review this function on occasion to check the viability of the file extension list. Consequently, ordering the file extensions alphabetically in the unlist code line makes this evaluation easier.

**Comment by oobianom** [comment]
Ok great, Brice. I will add these file types as well. Your response there also gave me an idea of what more to add to the documentation. I will list all the file types checked along with their full names.

**Comment by oobianom** [comment]
Wrapping up here. Hi Brice, you may check to make sure we align on the function as is, then I can close this issue.

**Comment by brichard1638** [comment]
The is.image function has been tested in quickcode version .6 for multi-element identification of image files. The test is based on the file extension type provided. In its current form, the function passed the unit tests. In addition, the documentation looks great!

The only feedback provided is to be able to add another nuanced condition to the is.image function. In the event that a file name contains no file extension, there is no condition response provided. For example, if a vector called x contains elements "img2.jpg," "northbound.xlsx,", and "landimg," the function in its current form would not be able to identify "landimg" because it has no file extension provided. The default value for this element would be FALSE but for a more nuanced and more accurate response, the value recommended should be NA. This response is more accurate since "landimg" could in fact be an image file, but for the missing file extension, the file is more appropriately categorized as NA instead of FALSE.

The FALSE value for "landimg" is not incorrect per se, but it is recommended that the more nuanced NA be provided. The value proposition in providing this extra condition is that the user, among reviewing for example, 1,000 file names would be able to very quickly identify whether or not there was a file naming convention error.

For example, executing the function table(x, useNA = "always"), will quickly identify the disparity in the vector's file naming convention.

**Comment by oobianom** [comment]
Great feedback. I need to think of how to best rewrite the function so that it returns NA for files without file name. No guarantees, but looking into it. Let me know if you come across a better way to rewrite it.

**Comment by oobianom** [comment]
I did find a fix and updated the code. Take a look when you have time.

**Comment by brichard1638** [comment]
I tested the latest version of the **is.image** function and it looks good! The documentation has been verified as having been changed to match the addition of the NA for those file names that do not contain a file extension.

Awesome!
