### ISSUE TITLE
Add Nuanced Functionality to the archivedPkg Function

### ISSUE THREAD

**Issue by brichard1638** [oobianom/quickcode#12]
Obi, please leave this issue open as I will come back to it and provide my remarks in the near future. There are a few areas of specificity that need to be addressed which will take some time to lay out.

I have not forgotten about this function!

**Comment by oobianom** [comment]
Great, Brice! Looking forward to any ideas you have to make this function better.

**Comment by oobianom** [comment]
Any further ideas in your mind for this functionality, Brice?

**Comment by brichard1638** [comment]
The following remarks are provided as feedback on two different, but related functions in the quickcode package, namely, **archivedPkg** and **rDecomPkg**.

Given that the **rDecomPkg** function was recently added in the last version update of quickcode, the original remarks intended to be applied under this issue have been somewhat mitigated.

Consequently, with the addition of the **rDecomPkg** function, a distinction has been drawn in quickcode between an archive and a decommissioned R package.

However, it is strongly recommended that another field be added to the output of the **archivedPkg** function. A third field, called **arch.status** would draw a clearer distinction between an archive and a decommissioned package. In its current form, it is not clear which packages contained in the data frame output are archived as prior versions compared to those that have been permanently decommissioned with no additional versions ever intended to be added to the CRAN archive.

A status indicator of **ARCH** or **DECOM** should be added to each R package to indicate its archive status.

It is believed that adding an **arch.status** field would substantially improve the value proposition of the **archivedPkg** function. 

The **rDecomPkg** function returns a binary value of either TRUE or FALSE to indicate whether a passed R package name has been decommissioned or not. However, there is a fundamental flaw in the logic underlying this function. As it turns out, there is no way to determine whether a package ever existed on CRAN or whether a package name holds a status that is active outside of CRAN but not decommissioned, in which it can be found on either another website or alternatively, on GitHub.

Optional solutions to this problem are recommended as follows:
- Make no changes to the **rDecomPkg** function but specifically document that the function ONLY checks packages on CRAN and does not include any packages outside the CRAN network. The problem with this approach is that the user has no way to determine whether a package ever existed on the CRAN network in the first instance. For example, the **printy** package is a popular R package that can be found on GitHub.
`rDecomPkg("printy")`
`[1] TRUE`
However, the function returns a TRUE value indicating the the **printy** package has been decommissioned. This is incorrect.
- Modify the **rDecomPkg** to return a string scaler instead of a binary response. Perhaps a change in the function name is also appropriate. For example, instead of **rDecomPkg**, the function could be changed to **rPkgStatus**. Possible **status** options returned are as follows:
1 "Active on CRAN"
2 "Decommissioned on CRAN"
3 "Not found on CRAN"

If this approach is applied, documentation should clearly state that if an R package is not found on CRAN it does not preclude the possibility that the package may exist in another form on an independent website or on GitHub.

**Comment by oobianom** [comment]
Happy new year, Brice! Hope you had a restful break. I have been very busy, still going to be for this month. However, I will tackle this issue as much as I can from this weekend. 

I like the idea of adding an argument named  arch.status and the rationale you've provided above. There are several ways to implement this functionality, but speed and performance would be affected. I will see the most efficient way to have it done for the next version, no worries.

As for the rDecomPkg function, I do not agree with a name change. However, I think you have a point regarding returning a more accurate response for a package that never existed on CRAN. My proposal is to add to what we currently have. What I mean by that is we will continue to return a TRUE or FALSE for packages that exist in CRAN. If a package never existed in CRAN, we will simply return an "NA" along with a warning message indicating that the package never existed in CRAN.

And of course, proper documentation is key!

**Comment by brichard1638** [comment]
I agree with the approach you have suggested for managing the rDcomPkg response. NA works for a pkg that never existed on CRAN!
________________________________

**Comment by oobianom** [comment]
Hi Brice, I have made some progress with rDecomPkg such that packages, which never existed in CRAN return NA. I have added an example for this as well.

**Comment by oobianom** [comment]
Hi Brice, I have now added the arch.status field to the archivedPkg function. I think the two prescribed modification have been done, take a look when you have some time.

**Comment by brichard1638** [comment]
I conducted basic testing on the **archivedPkg** function and it looks good! The only thing I would consider, not to be excessively obsessive about it, is to consider changing the **inactive** status found in the arch.status variable to **decom.** Decommissioned sounds like more of an appropriate label for packages that are no longer available on CRAN than an inactive label.

**Comment by oobianom** [comment]
Hey Brice, thanks for the quick test. I agree with you, and accordingly I have updated the values for *arch.status* to *active* or *decom*

**Comment by brichard1638** [comment]
When will the next version of quickcode be released?

I am hoping very soon!

________________________________

**Comment by oobianom** [comment]
Been very busy. We can certainly work on pushing out the next version by end of the month.

**Comment by oobianom** [comment]
This feature is all done and set.
