### ISSUE TITLE
Expand vector_pop Functionality

### ISSUE THREAD

**Issue by brichard1638** [oobianom/quickcode#2]
The **vector_pop** function provides the ability to remove the last n elements from a vector. This is a great function! It can both programmatically remove the last n elements from a vector, and controls for either independently storing the results or returns the remaining elements as a separate vector.

However, what it can't do which it should be able to do is extract the vector elements that were removed. Upon using this function, it did not appear to be possible to separately extract the last n elements from the target vector.

If it is currently possible to achieve this task, it is recommended that additional documentation be added to the function to showcase how this can be done.

If it is not currently possible, additional functionality should be added to the **vector_pop** function allowing this use case to be integrated into the function.

In addition, it is not clear how the el argument is to be used in the **vector_pop** function. It is recommended that the documentation be updated to include a coding example where this argument is used.

**Comment by oobianom** [comment]
That's a great point. I have worked on this expanded functionality and added examples as well. 
The user is able to specific the **ret="removed"** to get the removed elements.

The **"el"** argument allows the user to specific which elements to remove. Specifying the **"el"** ignores "n" argument.

This has been addressed!

**Comment by brichard1638** [comment]
Obi!

Awesome!

I have a few more proposal functions to add which I will do shortly.

I am looking forward to the next version of quickcode!

Brice
________________________________

**Comment by brichard1638** [comment]
Obi:::

I tested the vector_pop function with the changes you made. This is one powerful function! Wow!

The el argument is additionally powerful in that not only can you use the concatenate function to generate literal elements to remove, you can also use brackets to reference the element by its numeric placement. This is compelling to say the least. This is a really powerful function Obi!

I additionally tested the 'removed' value in the ret argument and found it to work as described.

The only concern I have about the structure of the vector_pop function is that the ret argument may be a little confusing for R users to understand. Typically, when a TRUE/FALSE value is called from within an argument, the presumption is that the argument value is binary in form. However, in the ret construction case, it is not. The accepted values are TRUE, FALSE, or removed. That comes across as very unorthodox in function construction.

However, the function in its current form works as described. While the structure of this function is unorthodox by R standards, it does in fact work! In a future version, you might want to consider restructuring this function to better describe the functionality you have captured. This means a future review of the function may require that it be reconstructed for ease of use.

It is argued that in its current form, both the el and the ret arguments are a little confusing to understand. However, the ideas supporting the technical capability of this function are genius and contribute to the extraordinary technology that is R.

Brice
________________________________

**Comment by oobianom** [comment]
Hey Brice, that's great to hear that the function works now as expected. 

I do agree with the unorthodox nature of the **ret** argument, let me know if you come up with any ideas on how to make it better.  Also agree that el and ret may be a bit confusing. Perhaps, in the future we can further refine this functionality.

**Comment by brichard1638** [comment]
Obi:::

I think to resolve the issue would require you to restructure the entire function. R is really about ideas and new ways of doing things so in that respect, the function is different but also fine. I would argue that so long as your documentation is adequate enough to explain how the function works along with sample code that applies the function, you should be okay.

Just to confirm that you are on the right track here, one of the most bizarre but eloquent R packages that I have ever experienced in terms of unorthodox and unique is the charlatan package. In that maintainer's case, there are parts of that package that I stumbled upon that were not documented!

The way that maintainer uses objects to generate functionality is really unique. In the case of the charlatan package, you must instantiate an object before you can use its functionality. That is incredibly unorthodox! But, it works and it is a powerful package if one is looking to work with simulated data.

Brice
________________________________
