### ISSUE TITLE
Error in the Return Date of the fAddDate Function

### ISSUE THREAD

**Issue by brichard1638** [oobianom/quickcode#20]
The **fAddDate** function returns an inaccurate date as part of converted file name.

The following code reproduces the error:
`library(quickcode)`
`Sys.Date()`
[1] "2024-03-21"

`fAddDate("ProgramOrgFileList.pdf")`
[1] "ProgramOrgFileList_03-Mar-2024.pdf"

The output should read:
"ProgramOrgFileList_21-Mar-2024.pdf"

Remediation: In the function's date format, the %m should be %d - small fix here to resolve.

**Comment by oobianom** [comment]
great catch! I just update the function now so that the data is accurate.

**Comment by brichard1638** [comment]
In evaluating the current state of the last changes made to the **fAddDate** function, would it be possible to add TWO arguments that would be used to customize the file date stamp configurations?

The idea is as follows:
Add a Boolean argument that includes the time as part of the date stamp:
Example: format(Sys.time(), "%d-%b-%Y %I%M %p")

Proposed Argument Name: **time = TRUE**
The default argument would include the time as part of the date time stamp.

Note: The colon was removed from the time configuration to allow it to be included as a viable file name.

----------------------------------------
Add a Boolean argument that includes the time zone as part of the date stamp:
Example: format(Sys.time(), "%d-%b-%Y %I%M %p %Z")

Proposed Argument Name: **zone = FALSE**
The default argument would not include the time zone as part of the date time stamp.

Note: The colon was removed from the time configuration to allow it to be included as a viable file name.

----------------------------------------
Recommendation: Remove the **tolower** function from the code as it is believed that it adds no value to the output.

**Comment by oobianom** [comment]
Hi Brice, overall I agree with your recommendation. I will remove the tolower.  As for the two new argument, I am thinking its best to just have one argument that allows the user to customize the date the way they want. Similar to what I currently did for the date3to1 function. I will set a default like 03-May-2024, but then the user can reformat how ever they'd like either to include time stamp or time zone and such.

**Comment by brichard1638** [comment]
Obi:::

Your idea is better than the one I suggested.

Okay!
________________________________

**Comment by oobianom** [comment]
Thanks, this is now updated and ready for your test to confirm that it resolves the issues.

**Comment by brichard1638** [comment]
Testing returned no errors. The **fAddDate** function executes and returns output as expected.
