### ISSUE TITLE
Retrieve the Creation Date of a GitHub Project

### ISSUE THREAD

**Issue by brichard1638** [oobianom/quickcode#21]
A search of a GitHub project creation date revealed that not one R function could be found that captures this value. While an exhaustive search was not conducted, a significant amount of time was invested not only in pursuing a function in R that could retrieve a GitHub repo creation date, but also a search on various GitHub repos in an attempt to locate a creation but to no avail.

As it turns out, it looks like the only way to identify this information, along with many other metadata points related to a GitHub repo, is through GitHub's API model.

The format used to retrieve a GitHub's project configuration file is a link as follows:
https://api.github.com/repos/reponamehere

For example, to view the GitHub API configuration file for the **quickcode** R package, see the following link:
https://api.github.com/repos/oobianom/quickcode

It would be a highly valuable capability if there was, at the very least, a function that could extract the repo creation date from the link page. A raw version of a function below can be used to extract this information. All that is needed is the name of the GitHub repo. The general structure of the function is provided below:

- Proposed Function Name: getGitHubRepoStart
- Number of Arguments: 1
- Argument Name: repo_name
- Argument Data Requirement: pass the name of a GitHub repo
- Functional Code Example:
`getGitHubRepoStart = function(repo_name){`
  `str = paste0("https://api.github.com/repos/", repo_name)`
  `read = readLines(str, warn = FALSE)`
  `pat = unlist(gregexpr("created_at", read)) + 13`
 `repocreated = as.Date(substr(read, start = pat, stop = pat + 13))`
  `return(repocreated)`
`}`

- Function Output: Creation Date of the GitHub repo
When the function executes, it returns the following result:
`getRepoStart("oobianom/quickcode")`
[1] "2023-06-28"

There is no error handling in this raw version of the function. It is currently designed to handle only repo names maintained on the GitHub platform.

Error handling should be added to the function that returns either an NA or some other message alerting the user that the passed repo name was not found on GitHub.

Other functions could be developed to extract additional metadata elements found on a GitHub API project page. A future function supporting **getRepoStart** could be to extract the top 10-15 data elements from the GitHub API page, returning the results in a data frame object.

**Comment by oobianom** [comment]
Hi Brice, great idea. I have created the getGitHubRepoStart as you recommended

**Comment by brichard1638** [comment]
When are you going to publish the latest version of quickcode?

I am looking forward to evaluating the new functionality.
________________________________

**Comment by oobianom** [comment]
Also, maybe we can extract the repository last modified date? another function like **getGitHubRepoChanged**

**Comment by oobianom** [comment]
As for publishing, I have yet to finish the function for getting distribution of a data, and also incorporate your suggested distribution. So maybe we can aim for May sometime for v0.8

**Comment by brichard1638** [comment]
Absolutely!

I provided a sample api GitHub link where you can review the data points captured. Any number of GitHub-based functions can be developed that address various aspects of the state of a GitHub project.

I chose the low-hanging fruit of a GitHub project to consider.
________________________________

**Comment by brichard1638** [comment]
Why not just publish a version in the next day or two and let the other ideas be included in a subsequent version. You current schedule is to publish about once a month. Given the amount of new material we are adding, I think that schedule is most appropriate. It allows us to apply the new functionality while developing new functional capabilities.
________________________________

**Comment by oobianom** [comment]
okay, that's actually a good idea. I can wrap a few functionality up and then we can publish. help me in building up the documentation for getGitHubRepoStart. I currently have brief draft in it for now, so take a look and let me know what needs to be added. I will work on finalizing other functions. Then I can send something for publishing tomorrow or next.

**Comment by brichard1638** [comment]
Will do.
________________________________

**Comment by brichard1638** [comment]
One more thing. Not sure what you mean by "have brief draft in it for now." I am not sure what that means. Can you copy and paste the content you do have so I can look at it and amend it as needed?
________________________________

**Comment by oobianom** [comment]
Oh, I meant that you can install the current repo update and use ??quickcode::getGitRepoStart to view the documentation I currently have in it

**Comment by oobianom** [comment]
<html>
<body>
<h2 style="font-size: x-large; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Fetch GitHub repository Creation Date</h2><h3 style="color: rgb(89, 89, 89); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Description</h3><p style="color: rgb(0, 0, 0); font-family: sans-serif; font-size: 13.3333px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Get the information of when the repository was created</p><p style="color: rgb(0, 0, 0); font-family: sans-serif; font-size: 13.3333px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Get the information of when the repository was last changed</p><h3 style="color: rgb(89, 89, 89); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Usage</h3><pre style="color: rgb(0, 0, 0); font-size: 13.3333px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">getGitRepoStart(repo_name, out.format = "%Y-%m-%d")

getGitRepoChange(repo_name, out.format = "%Y-%m-%d")
</pre><h3 style="color: rgb(89, 89, 89); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Arguments</h3>
repo_name | name of the repository
-- | --
out.format | date output format

<h3 style="color: rgb(89, 89, 89); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Value</h3><p style="color: rgb(0, 0, 0); font-family: sans-serif; font-size: 13.3333px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">date of creation of repository as a character</p><p style="color: rgb(0, 0, 0); font-family: sans-serif; font-size: 13.3333px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">date of creation of repository as a character</p><h3 style="color: rgb(89, 89, 89); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Examples</h3><pre style="color: rgb(0, 0, 0); font-size: 13.3333px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">getGitRepoStart("oobianom/quickcode")

getGitRepoStart("cran/dplyr")

getGitRepoChange(repo_name="oobianom/quickcode")

getGitRepoChange("cran/dplyr")</pre>
</body>
</html>

**Comment by brichard1638** [comment]
The proposed description for the getGitRepoStart and getGitRepoChange functions in the quickcode package:

PROPOSED DESCRIPTION
"The GitHub REST API is a powerful tool that allows developers to interact with GitHub programmatically. It provides a set of endpoints that allows a user to create integrations, retrieve data, and automate workflows related to GitHub repositories. It is a means by which users can interact with GitHub without directly using a web interface.

Two functions in quickcode are provided to extract important temporal information about a GitHub repository. For example, the getGitRepoStart function is used to retrieve the date a GitHub repository was first created.

The getGitRepoChange function returns the date a GitHub repository was last updated.

The out.format argument provided in each function uses standard R-based date encoding to customize the format of the returned date."

EXAMPLES:
getGitRepoChange(repo_name = "oobianom/quickcode", out.format = "%d-%b-%Y")
getGitRepoChange(repo_name = "oobianom/quickcode", out.format = "%Y/%m/%d")
getGitRepoStart("repo_name = oobianom/quickcode", out.format = "%j|%Y")

________________________________

**Comment by brichard1638** [comment]
Use this blurb which I think is better:

The proposed description for the getGitRepoStart and getGitRepoChange functions in the quickcode package:

PROPOSED DESCRIPTION
"The GitHub REST API is a powerful tool that allows developers to interact with GitHub programmatically. It provides a set of endpoints that allows a user to create integrations, retrieve data, and automate workflows related to GitHub repositories. It is a means by which users can interact with GitHub without directly using a web interface.

Two functions in the quickcode package utilize the GitHub REST API to extract important temporal information about a GitHub repository. For example, the getGitRepoStart function is used to retrieve the date a GitHub repository was first created.

The getGitRepoChange function returns the date a GitHub repository was last updated.

The out.format argument provided in each function uses standard R-based date encoding to customize the format of the returned date."

EXAMPLES:
getGitRepoChange(repo_name = "oobianom/quickcode", out.format = "%d-%b-%Y")
getGitRepoChange(repo_name = "oobianom/quickcode", out.format = "%Y/%m/%d")
getGitRepoStart("repo_name = oobianom/quickcode", out.format = "%j|%Y")
________________________________

**Comment by oobianom** [comment]
Thanks, will incorporate.

**Comment by oobianom** [comment]
I believe we addressed this issue. Or do we want to creation more functions to extract other information from this Github output? What do you think?

**Comment by brichard1638** [comment]
My personal opinion on GitHub metadata is that you have captured the most important GitHub metrics - the repo start and change dates. I would look for feedback from others in the R community as to whether additional GitHub metrics should be captured. Is there an interest and if so, which GitHub metrics should be considered?

At this juncture, I would not move to add any more functions related to this feature.
________________________________

**Comment by oobianom** [comment]
Well said, Brice. I agree.
