### ISSUE TITLE
Error in Output of archivedPkg Function

### ISSUE THREAD

**Issue by brichard1638** [oobianom/quickcode#22]
It appears that the **archivedPkg** function is returning incorrect data. In at least one instance, the arch.status value has been incorrectly defined as "decom" when the package is clearly active on CRAN.

To reproduce this particular error, execute the following code:
`library(quickcode)`
`x = archivedPkg()`

`grep("funModeling", x$name)`
`[1] 6789`

`x[6789,]`
 
Now navigate to a package name called **funModeling**. The archive status for this package reveals that has been decommissioned. In fact, that package is currently active.

https://cran.r-project.org/web/packages/funModeling/index.html

**Comment by oobianom** [comment]
Hi Brice, please note that the data provided by this function is pulled from https://quickcode.obi.obianom.com/CRAN . 
I have an automated script that creates the update every other day. So it is possible that the package was previously inactive, and just got re-activated. The update from this morning indicates that x[6789,] actually shows that the package is active.

**Comment by brichard1638** [comment]
Fair enough. When I executed the function earlier today it showed that the funModeling package was decommissioned. What this tells me is that my tool for monitoring R technology is more actively current than R's archive repository.No changes to be made then. There is just a lag in the archive repository update.My apologies.On Apr 1, 2024 12:44 PM, Obi Obianom ***@***.***> wrote:
Hi Brice, please note that the data provided by this function is pulled from https://quickcode.obi.obianom.com/CRAN .
I have an automated script that creates the update every other day. So it is possible that the package was previously inactive, and just got re-activated. The update from this morning indicates that x[6789,] actually shows that the package is active.

**Comment by oobianom** [comment]
No problem, thanks for checking.
