### ISSUE TITLE
fAddDate Fails When Referencing a Variable

### ISSUE THREAD

**Issue by brichard1638** [oobianom/quickcode#23]
The **fAddDate** function fails when the file name to which it is referenced originates from a variable contained in a data frame object.

Expected Behavior: The **fAddDate** function should correctly process scaler and vector inputs. Variable data originating from within a data frame object should also be included as an input. In its current form, a variable reference return incorrect output.

The code below reproduces the error defining this issue:
`library(quickcode)`
`data("USArrests")`
`USArrests$fn = paste0(row.names(USArrests), ".txt")`
`head(fAddDate(USArrests$fn),2)`

**Comment by oobianom** [comment]
Thanks Brice. I will get to this and the rest of our unresolved issues a bit later. I am extremely busy this month.

**Comment by brichard1638** [comment]
Feel free to reach out if you are having a challenge at work that might require an R response.

There are actually a few pharmacokinetic-based packages found in R. They are as follows:

  *
clinPK: Clinical Pharmacokinetics Toolkit
  *
wnl: Minimization Tool for Pharmacokinetic-Pharmacodynamic Data Analysis
  *
ncar: Noncompartmental Analysis for Pharmacokinetic Report

________________________________

**Comment by oobianom** [comment]
I am resuming work on this package again this weekend

**Comment by brichard1638** [comment]
Great:::

I have put another idea for you to consider by way of a new function.


________________________________

**Comment by oobianom** [comment]
This is now resolved and the repository in now updated. Brice take a look when you have some time, Thanks.

**Comment by brichard1638** [comment]
Awesome job!

The **fAddDate** function has passed all the tests under which it was evaluated. This includes both a vector and a variable test.

In addition, a formatting test was conducted which included characters exclusive of date-based R formatting parameters. For example, encapsulating an open and closed parenthesis within the date. The function also passed that test.

**Comment by oobianom** [comment]
Thanks Brice, great we fix issues with this function. I use it almost daily now in my scripts.
