### ISSUE TITLE
Add a Function that Calculates Z-Scores

### ISSUE THREAD

**Issue by brichard1638** [oobianom/quickcode#25]
I wonder if you would consider adding a quick, much needed function into the next version of quickcode.

I was shocked to discover that a fairly comprehensive search online using Google did NOT reveal a function in R that returns the Z-score from a distribution of numeric values.

There exists various functions similar to the Z-score in R that can be modeled as a component characteristic for a distribution but I was not able to find any function that generated a quick set of Z-score values.

It is therefore proposed that a Z-score function be added to the **quickcode** package.

DEFINITION
- In statistical modeling, a Z-score is a set of measures that represent how many standard deviations from the mean each corresponding value is within a distribution. An alternative definition is that a Z-score is a statistical measure that quantifies the distance between each data point and the mean within a targeted distribution.

PROPOSED FUNCTION INFORMATION
- The proposed function name is **zscore**
- The total number of arguments contained within the function is 1
- Proposed argument name is **var** for a passed variable

FUNCTIONAL STRUCTURE
- The baseline function is represented as follows:
`zscore <- function(var) {`
  `rounded_result <- round((var - mean(var, na.rm = TRUE)) / sd(var, na.rm = TRUE), 2)`
  `return(rounded_result)`
`}`

FUNCTION TESTING
- The function as described has been successfully tested to return accurate results

ADDITIONAL NOTES
- Additional error handling should be provided to ensure that only numeric values are passed to the function; any variable that is passed to the function that is not of class numeric or integer should return an error message
- Another argument could be added that controls the number of digits to which the z-scores are rounded

EXAMPLE
- Capture z-scores from the following distribution x 
`x = c(6, 7, 7, 12, 13, 13, 15, 16, 19, 22)`
`z_scores = zscore(x)`
`df = data.frame(val = x, zscore = z_scores)`

EXPLANATION
- The first data value of “6” is 1.32 standard deviations **below** the mean (-1.32)
- The fifth data value of “13” is 0 standard deviations away from the mean, returning a value of 0.00; this means the corresponding value represents the mean of the distribution itself
- The last data value of “22” is 1.70 standard deviations **above** the mean (1.70)

SOURCE REFERENCE
https://www.statology.org/z-score-r/

**Comment by oobianom** [comment]
Great idea. It's interesting that you bring up this idea of calculating z-score. I was just talking to my colleague about pediatric z-score yesterday. Let's add it, but I also want read up more on z-score and how that's interpreted across various fields.

**Comment by brichard1638** [comment]
Let me add a little more context to this issue. As it turns out, there is a really significant difference between a Z-score and a Z Test.

I don't know if you were also discussing a Z Test with your colleague when you referenced a Z-score but they it is certainly possible to apply both of them when conducting hypothesis testing.

Consequently, a wonderful function that can be used to conduct a Z Test is found in the DescTools package.

In that package, see the function titled, "ZTest."

The intent with my proposal was to create a quick function that is independent of Z testing but certainly could be used to compliment it.

Brice
________________________________

**Comment by oobianom** [comment]
Hey Brice, I finally got what I was referring to. So not Z test, but Z-score calculations from growth charts. We use these for pediatric generation of virtual patients. The particular reference page and calculation is captured here: https://www.cdc.gov/growthcharts/cdc-data-files.htm

I don't supposed its the same thing we are doing here, so im thinking if we should also include that, and how we should name to avoid confusion.

**Comment by brichard1638** [comment]
You are correct. The calculations you provided in the cdc link relative to growth charts is **completely** different from the function I suggested.

I think BOTH functions should be included.

My recommendation of a function name for your grown chart function, if you should decide to include it, is as follows:
**ZscoreGrowthCurve**

**Comment by oobianom** [comment]
Okay great. I like this function name. I will include it as well for zscore calculation.

**Comment by brichard1638** [comment]
Obi:::

When were you planning on releasing the latest version of quickcode? I have several new functions I wanted to introduce but I wanted to wait until after 0.9 was released.


________________________________

**Comment by oobianom** [comment]
Aiming for release end of next weekend. I think we can make it with a few new functions.
