### ISSUE TITLE
Extract the IP Address Being Used on the Current Machine

### ISSUE THREAD

**Issue by brichard1638** [oobianom/quickcode#28]
I have recently been pursuing the possibility of developing R functions in support of facilitating cybersecurity-based tasks. As it turns out, there is a dearth of functions in R that address this need. To that end, I thought I would present a few ideas for your review and consideration to be included in the next version of **quickcode.**

In the area of security, I asked a basic question. Using R, how easy would it be to get a simple IP address of the machine currently connected to the internet? One would think that such a function would exist in R. However, I was unable to find a single function that could execute this simple task.

**FUNCTION IDEA**
This idea proposes to generate an R function that can be easily deployed to extract the user's current IP address.

**RECOMMENDED FUNCTION NAME**
getMYIP

**TOTAL NUMBER OF FUNCTIONAL ARGUMENTS**
0

**FUNCTION STRUCTURE**
`getMYIP <- function() {`

  `# Get vector element of machine's local IP address`
  `loc <- grep("IPv4", system("ipconfig", intern = TRUE))`
  `ip <- system("ipconfig",intern = TRUE)[loc]`

  `# Match an IP address pattern`
  `ip_pattern <- "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b"`
  
  `# Extract the occurrence of an IP address`
  `extracted_ip <- regmatches(ip, regexpr(ip_pattern, ip))`
  
  `# Return the extracted IP address (or character(0) if not found)`
  `return(extracted_ip)`
`}`

**TEST STATUS**
The function, as defined under the **FUNCTION STRUCTURE** section of this issue has been tested, yielding accurate results. However, more testing should be conducted on more internet-connected machines to verify both its accuracy and functional utility.

**NOTE**
Testing revealed that more than one IPv4 address may be returned. This is largely contingent on how the machine's network connections have been configured.

**Comment by oobianom** [comment]
I really like the idea of this function. Many times, I want to know my IP... usually I just google it, but it is cool to easily fetch it with a function. It will be of good utility in developing shiny apps or dashboards, to say the least.

**Comment by brichard1638** [comment]
👍
________________________________

**Comment by oobianom** [comment]
I wonder why the output of the IP from the current function does not match my output when I google "my ip" or search it at https://whatismyipaddress.com/

**Comment by brichard1638** [comment]
I would NOT trust a Google search for you IP.....never....to verify the output provided by my R function, go to your command line and enter "ipconfig." The IP returned should match the IP in the R function.
________________________________

**Comment by oobianom** [comment]
Got it. yes it does match the one from my command prompt. So then what is that particular IP provided by https://whatismyipaddress.com/ and Google supposed to be?

The reason I am curious about this is that I forsee myself using this function in developing shiny apps and dashboards, so I just wonder what various outputs of IP really mean. I mean I see here that we are giving IPv4. I wonder if google is giving another type of IP.

**Comment by brichard1638** [comment]
Preliminary research on this issue revealed the following:

"Your public IP is your router's IP, so in most cases, your public IP is the same as your router IP. However, it's possible for them to be different if your router is not connected to the Internet."

All I will say is that I trust what the command line says on my OWN box about my IP not some website which I cannot vet in terms of their backend code to see what is being done to determine the output generated.



________________________________

**Comment by oobianom** [comment]
Thank you for looking further into this Brice! Thanks for the explanation and I agree with you.

**Comment by oobianom** [comment]
This function has also been flagged by CRAN to be remove because of the issue with "ipconfig"

**Comment by brichard1638** [comment]
Well I guess you should drop that function as well. This is quite disappointing that R has so many restrictions on its functions.

I understand the importance of standards but this is too much in my opinion. There should be a way for R to make a distinction among its users that certain packages run ONLY ON certain OSs. The fact that they want to standardize very damn function to run on every possible machine configuration is a constraint too far.

This is why I will am currently moving to develop my own OFFLINE R package so that I can benefit from these "outlier" functions.

I think you should consider doing the same. There's no reason why one can't benefit from running functions that ONLY execute on, for example, a Windows box.

Anyway, enough ranting here. My recommendation would be for you to drop any and ALL functions that appear to be flagged by CRAN due to the lack of universality of function execution.

For example, any function attempting to benefit from command line functionality and switches falls into this category because they are unique to Windows. This would include ideas on functions I had earlier presented to you on netstat and active user-IP acquisition.

Just to be ahead of the curve, I would also recommend that you drop the genRandImg function because trying to do anything remotely interesting in R that leverages the internet directly is going to eventually get flagged.

Brice
________________________________

**Comment by oobianom** [comment]
I understand your frustration about the standards. I run both a Windows and Linux OS, but I barely use the Linux OS for R development. So I primarily care packages that run effectively on Windows.

That said, to ensure that we keep the package on CRAN and still try to include some of these functions (because I personally find them useful), I will try to see if I can modification the function with alternative for Linux and see if it gets accepted by CRAN.

**Comment by oobianom** [comment]
could not find a suitable revision across all platforms for this function. the issue is the "ipconfig".
