### ISSUE TITLE
Add a Function that Returns R Color Constants as a Named Vector & as a Plot

### ISSUE THREAD

**Issue by brichard1638** [oobianom/quickcode#5]
Where is there a quick R function that can be used to retrieve an ordered listing of R color constants? Currently, there isn't an R function that can be used to achieve this task. The closest R function I was able to find was a function called **labels2colors** found in the moduleColor package. The problem is that the moduleColor package maintains a dependency to a package called impute which is no longer actively available on CRAN but has been archived. So, essentially, this function, along with its corresponding package is defunct. While it is still possible to access functions from the moduleColor package, it is not achievable without having to initiate an extra effort to access a single desired function.

As a result, it is recommended that a function be developed in the quickcode package that achieves two outputs as outlined below:
1) Returns a Named Vector of R color constants called **recolorconst**
2) Plots a swatch of R color constants

Function Name Recommendation: **rcolorconst**

Code Body: The essence of the code supporting this proposed function is provided as follows:
`rcolorconst = c("black" = 1, "red" = 2, "green" = 3, "blue" = 4, "cyan" = 5, "magenta" = 6, "orange" = 7, "gray" = 8)`
`rcolconst = c("black", "red", "green", "blue", "cyan", "magenta", "orange", "gray")`
`Polychrome::swatch(rcolconst, main = "R Color Constants")`

While this proposed function would create a dependency on the Polychrome package, it is believed that the utility of this function outweighs the inconvenience of introducing a dependency to quickcode.

Function Arguments: To keep it simple, there are no proposed arguments to the **rcolorconst** function. To execute the function, just type **rcolorconst()**

**Comment by oobianom** [comment]
I will work on this now. As much as possible, I try not to add dependency to another package if I am not taking a lot of functions from that package. So let's see here.

**Comment by brichard1638** [comment]
The idea behind rcolconst is that it was passed as a vector to the swatch function to generate a color constant plot. Conversely, the rcolorconst was configured to return a Named Vector.

Consequently, the code I provide is really pseudo code that is designed to convey the intent of the proposed function. It is not really designed to be a literal interpretation of the code that will ultimately be used - it may or may not be code that is included in the final function. That is left up to you and your functional design capabilities.

I was showing the distinction in the two outputs comprising the function. Namely, a Named Vector (using rcolorconst) and then a plot which uses the rcolconst vector.

If you can generate a function that generates both outputs with a single vector, then apply that approach.

I hope this response answers your question.

**Comment by oobianom** [comment]
Hi Brice, thanks for the clarification. I have written a draft function rcolorconst(). Let me know if this is what you envisioned.

**Comment by brichard1638** [comment]
Obi:::

I tested the rcolorconst function that you provided. There are some challenges with its current output.

Let me provide a deeper explanation of the intent driving the need for this function.

As it turns out, R has 8 values called color constants that can be used as a "short-cut" method for colorizing a plot. So, instead of using an RGB function, hexadecimals, or color literals, one can decide to employ color constants. These numeric color values range in R from 1-8 only.

A practical use case and an example in which R's color constants can be deployed is demonstrated in the following code:

x = data.frame(meas = rnorm(20), grp = sample(1:5, size = 20, replace = TRUE))
plot(x, pch = 16, col = x$grp)

So, instead of using other color representations, one can enjoy the use of color constants for plot colorization. In this example, the scatterplot is colorized using five (1-5) R color constants.

However, the problem here is that it's not an easy task to discern what color is represented by each numeric value.

So, the objective in providing an rcolorconst function is two-fold:

  *   Textually show how the numeric values correspond to colors
  *   Graphically create a plot that showcases the relationship between numeric color constants and their corresponding colors

So, the textual output for rcolorconst should be a Named Vector which returns the textual version for this task and for the graphic version, a plot is provided. To generate an appropriate plot visualization, I recommend using the swatch function found in the Polychrome package because you get the numeric values contained within each colorized bar for free. This means that you don't have to execute any additional code to define the color constants.

In the original post recommending this function, you can find pseudo code that supports this explanation.

If you want to remain free of the package dependency, your plot needs to return each colorized bar IN ADDITION to which there are numeric values contained within each bar from 1-8 that establish and provide the color constant relationships to the colors they represent.

If you can do this without deploying a dependency, that's great. However, if you are struggling to achieve this absolute requirement, then a dependency call to the Polychrome package may be needed.

The following information is provided in support of the Polychrome package:

As of 24-Sep-2023

R Package Name.............................................Polychrome
Number of Days Since Last Pkg Update..........509
First Pkg Release Date.....................................17-Mar-2017
Latest Pkg Release Date...................................03-May-2022
Total Versions Released to Date......................14

Brice



________________________________

**Comment by brichard1638** [comment]
Obi:::

Absolutely! Upon request, I will provide proposed content to support the documentation for any of these functions.

Let me look at the changes you made to the rcolorconst function, and I will respond accordingly with a paragraph or two of supportive documentation.

Brice
________________________________

**Comment by brichard1638** [comment]
Obi:::

I ran the code and the output still isn't correct. I tried replicating the function code you provided which is very similar to the original code I provided you. When THAT original code is executed outside a function, it returns the output as expected. However, when it is executed from within the function structure you provided, it is not correct.

I believe that your function is going to have to be reconstructed to return the correct results.

Moving forward, perhaps the best way to tackle this problem is to show you what the results SHOULD look like relative to the rcolorconst function. The code I provided may not fit the structure of code required for this function.

So, the rcolorconst function should return TWO outputs with the only argument being a title argument for the color palette plot that contains a default title of R Color Constants:

OUTPUT OBJECT 1
This output object should return a Named Vector. The results should return the following data object configured to the following specification:

x =  rcolorconst()
x
black     red   green    blue    cyan   magenta  orange    gray
       1         2           3          4          5                6            7          8


OUTPUT OBJECT 2
This output object returns a plot that is generated from the swatch function found in the Polychrome package. The plot should look like the following:
[cid:8898b0ee-2759-4fe7-afe9-ee90acc398b9]
As the plot shows, the numeric values correspond to those represented by the Named Vector, the first object returned.

I'm not sure what the functional code looks like to generate these output objects, but it appears that the initial code I provided does not work in a function. In any event, this is what I was conceptualizing as the final output for this function. If you can figure out how to create these outputs consistent with this data configuration, perhaps without using a dependency package, that would be great! I hope this explanation is helpful.

Brice
________________________________

**Comment by brichard1638** [comment]
Obi:::

Consistent with your request, I will provide documentation for the rcolorconst function once we have a working function.

I want to ensure that you are still in agreement on developing and implementing this function in the quickcode package.

Brice
________________________________

**Comment by oobianom** [comment]
I totally missed your comments above, somehow. That's for the reminder. I will work on it further later today. By they way, the embed plot in your comment does not show up. It only shows up as "[cid:8898b0ee-2759-4fe7-afe9-ee90acc398b9]". Also, did you prepare a documentation yet to be added to the function?

**Comment by oobianom** [comment]
Actually, getting ahead of this. I updated the function just now based on some of your comment above. You can test it and see if we got the function right now.

**Comment by brichard1638** [comment]
Obi,Seeing that graphic plot will help better explain the function to you. Do you have a personal email address where I can send the explanation of the rcolorconst function to you?You should be able to see the function explanation in its entirety through a personal email address.Please advise.Send your personal email address to me at my personal email address as ***@***.*** Sep 28, 2023 3:35 PM, Obi Obianom ***@***.***> wrote:
I totally missed your comments above, somehow. That's for the reminder. I will work on it further later today. By they way, the embed plot in your comment does not show up. It only shows up as "[cid:8898b0ee-2759-4fe7-afe9-ee90acc398b9]". Also, did you prepare a documentation yet to be added to the function?

**Comment by brichard1638** [comment]
Obi:::

I ran the latest version of quickcode to test the rcolorconst function.

As it turns out, the graphic you generated works and returns the plot visualization as expected.

However, the only bug that remains is converting the output as a Named Vector.

The current output returns the following values as an object of class matrix:


[,1]
[1,]  0.7
[2,]  1.9
[3,]  3.1
[4,]  4.3
[5,]  5.5
[6,]  6.7
[7,]  7.9
[8,]  9.1

Both the output and its corresponding class are incorrect. The class should be a Named Vector and the results, when converted to a data object, should return the following values:
x =  rcolorconst()
x
black     red   green    blue    cyan   magenta    orange    gray
       1         2           3          4          5                6              7          8

We are almost there!

Brice
________________________________

**Comment by brichard1638** [comment]
Obi:::

Documentation for the rcolorconst function is forthcoming.

Brice
________________________________

**Comment by brichard1638** [comment]
I tested the following code and this is **exactly** what is needed to fulfill this requirement for rcolorconst:
`function (title = "R Color Constants") `
`{`
  `rcolorconst = c(`1` = "black", `2` = "red", `3` = "green", 
                 ` `4` = "blue", `5` = "cyan", `6` = "magenta", `7` = "orange",
                  `8` = "gray")
  `Polychrome::swatch(rcolorconst, main = title)`
  `nv = c("black" = 1, "red" = 2, "green" = 3, "blue" = 4, "cyan" = 5, "magenta" = 6, "orange" = 7, "gray" = 8)`
  `return(nv)`
`}`

**Comment by oobianom** [comment]
Better yet, I used the setNames function. Check out the update now.

**Comment by brichard1638** [comment]
Not to be excessively precise or detailed, but using the setNames function converts the returned object as a character class. The values should be a Named Vector as a numeric class. That's why I encoded the nv object as I did. Consequently, the setNames function is designed to work with vectors of class character.

It's a very small detail, but one that I think matters. I am hoping that you agree.

Compare my function to yours to return the different classes between them.

**Comment by brichard1638** [comment]
Once your decision has been made on how to handle the Named Vector in the rcolorconst function, I think you will be ready to publish!!! 😊

**Comment by brichard1638** [comment]
One last comment on the rcolorconst function. If you want to use the setNames function, I recommend encoding the nv variable as follows:

`nv = setNames(object = 1:8, nm = c("black", "red", "green", "blue", "cyan", "magenta", "orange", "gray"))`

This will return the data object as a Named Numeric Vector. 😊

**Comment by oobianom** [comment]
Instead of redeclaring the color names, I just added as.numeric in the set names and that achieved the same result. This should be good to go.

**Comment by brichard1638** [comment]
Obi:::

Oh my goodness! I forgot initially to provide you with the documentation your requested for the rcolorconst function.

I will work on that and provide that to you shortly.

Brice



________________________________

**Comment by brichard1638** [comment]
Obi:::

The following content is designed to support the documentation needed for the rcolorconst function and is provided as follows:

DESCRIPTION:
This function provides information that describes the color constants that exist in R. In addition to the color palette in R that can be represented as either color literals or hexadecimal values, numeric values can also be used to add colorization to a plot. Numeric values ranging from 1 to 8 provide 8 basic colors that can be deployed. The rcolorconst function returns both a Named Vector and a color palette plot that connects these numeric values with their corresponding color.

EXAMPLES:
set.seed(200)
x = data.frame(meas = rnorm(20), grp = sample(1:8, size = 100, replace = TRUE))
plot(x, pch = 16, col = x$grp)

colnums = rcolorconst()

Let me know if you need anything else.

Brice
________________________________

**Comment by oobianom** [comment]
Fantastic, thanks for suggesting and helping get this function constructed. I will incorporate these.
