### ISSUE TITLE
Generate a Listing of All CRAN Archive Packages

### ISSUE THREAD

**Issue by brichard1638** [oobianom/quickcode#6]
In working with many archive packages and the various states in which packages can be installed or loaded, it appears that there is not one function in any of the R-based processing packages that allows a user to extract an R package archive listing.

This includes packages such as crandep, cranlogs, dlstats, groundhog, packagefinder, pacman, pkgsearch, remotes, report, or rversions. There may be a function out there that addresses this issue but if there is, it is obscurely positioned.

It is therefore proposed that a function be created that returns a data frame that lists all archived R packages including the name and the date the package was archived.

The URL where this information can be retrieved is as follows:
https://cran.r-project.org/src/contrib/Archive/

The function could be called r_arch, arch_r, archpkg or a function name that supports this process action.

**Function Arguments**
In terms of arguments, it might be useful to provide an argument that determines whether the output is returned as either a data frame or as a Named Vector. An additional argument could be added that allows the user to return only a listing of archive package names or a listing of the package names AND their corresponding archived dates. Returning the results as a list object is another potential option to consider.

**Comment by oobianom** [comment]
I agree with inclusion of a function or maybe even more with regards to archived packages. Do you currently have a working code that I can build on for this particular functionality?

**Comment by brichard1638** [comment]
Obi:::

I do not. I gave you all that I had that supports this idea which is the CRAN archive site.

Brice
________________________________

**Comment by oobianom** [comment]
Hey Brice, I have a draft function ready. Something simple, get the job done and the link will be automatically updated.
current draft function name: archivedPkg

**Comment by brichard1638** [comment]
Obi:::

I tested the archivedPkg function and here's what the testing revealed:

  *   The function currently runs end-to-end without failing
  *   The documentation suggests that there is an n argument but I was only able to identify one argument called "startsWith"
  *   The function, in its current form, only seems able to extract groups of archived R packages beginning with a single character letter such as "c" or "s"
  *   When no value is set in the "startsWith" argument, only 883 package names are returned; given the total number of archived packages available, this is an incomplete list; it appears that the default extraction if no value is set for the "startsWith" argument is archived packages beginning with "a"
  *   The function returns a data object of class data.frame consisting of two variables - name and latest.archive - this result passes the output test

Brice
________________________________

**Comment by brichard1638** [comment]
Obi:::

One more thought on the archivedPkg function:

  *   In addition to the character filter that currently exists within the function, another filter worth considering is to extract a subset of the archived R packages after a certain date; perhaps an argument called "after" that accepts a two-digit month and a four-digit year would be appropriate:

           Example: archivedPkg(after = "05-2020")

           You could also consider providing a "before" argument but that may complicate the function. An "after" argument should be sufficient.

Brice
________________________________

**Comment by oobianom** [comment]
Brice, your response was fast. Thanks.
I will address them this week as I get time after work office hours.

**Comment by oobianom** [comment]
Hi Brice, I have revised the function now. Can you take a look when you get a chance.

**Comment by brichard1638** [comment]
Obi:::

I have tested the archivedPkg function in the latest version of quickcode. Great work! However, I did find a few issues that should be considered. Here is what my testing discovered:

  *   The archivedPkg function ran end-to-end without crashing or generating an error; various argument configurations were tested including startsWith, after, inc.date, and as
  *   The output, irrespective of configuration, appeared to be generated with a high degree of performance
  *   The output, irrespective of configuration, appeared to generate accurate results
  *   There were only two issues found with the archivedPkg function

ISSUES FOUND

  *   The argument value options for "as" are currently either 'data.frame' or 'vector;' however, the vector value is miscategorized. When the function executes with the 'vector' value entered in the as argument, a data object of class list is returned, not a vector. Therefore, it is recommended that the argument values for the as argument be 'data.frame' and 'list'
  *   In the data frame generated by the achivedPkg function, the variable called 'latest.archive' returns an object of class character; because the data returned are dates, it is recommended that the class for this variable be encoded as either Date or 'POSIXct' 'POSIXt' using as.POSIXct
  *   If the 'latest.archive' variable is encoded as class Date, the time stamp will be truncated; if this variable is encoded as class 'POSIXct' 'POSIXt,' both the date and its corresponding time stamp will be included; it is recommended that the 'latest.archive' variable be encoded as an object of class Date

Brice
________________________________

**Comment by oobianom** [comment]
Thanks for testing and for the feedback. I have revised the function based on your feedback.

**Comment by brichard1638** [comment]
Obi:::

I conducted some testing on the archivedPkg and it looks good!

It passed all the tests I conducted on it.

👍

Brice
________________________________

**Comment by oobianom** [comment]
Fantastic! Thanks. This is all set for the next version.

**Comment by brichard1638** [comment]
Obi:::

What about the status of the rcolorconst function? Are you still working on developing that function?

Was my follow-up explanation helpful?

Brice
________________________________
