### ISSUE TITLE
Add a Vector of Categories Supporting the genRandImg Function

### ISSUE THREAD

**Issue by brichard1638** [oobianom/quickcode#7]
It is not clear what the range of possibilities are in support of the categories used in the genRandImg function. The current documentation example for this function provides a few categories supporting the cat argument but the examples are incomplete.

It is therefore proposed that a separate vector called keycat be included in the quickcode package that provides a listing of possible categories available for use in the genRandImg function.

It is believed that it is **NOT** clear to the user what categories are available for use, other than those provided in the current documentation.

The following categorical keywords, alphabetically sorted, have been tested with the genRandImg function and work as intended:

`keycat= c("3D", "animals", "architecture", "backgrounds", "beauty", "experimental", "fashion", "film", "food", "interior", "nature", "people", "renders", "school", "sports", "travel", "unsplash", "wallpapers")` 

The keycat vector should be an object of class character.

There are currently (18) active categories that can be applied to the genRandImg function.

A proposed example of how this vector of class character could support the genRandImg function:

`library(quickcode)`
`fp = paste0(path.expand("~"), "/images")`
`keycat()`
`genRandImg(fp, cat = keycat[9], n = 5)`

**Comment by oobianom** [comment]
I just added this revision in a recent submission request by CRAN. They raised some issues about v0.4 and requested a re-submission to avoid the package from being taken off CRAN. So in addressing the issues, I included this bit of update. Thanks for this suggestion.

**Comment by brichard1638** [comment]
Okay, so I reviewed the latest package version of quickcode. I see you added documentation that outlines all the possible categories. This is good! The only thing I would add to this approach, which is inherently different from the proposed idea I offered, is to actually add the code for the user to use to independently create his/her own vector of categories.

For example, at the end of the **Category Choices** documentation provision, add the following content:

"For example, store all categories into a single vector for a cross-reference made available to the cat argument:
keycat= c("3D", "animals", "architecture", "backgrounds", "beauty", "experimental", "fashion", "film", "food", "interior", "nature", "people", "renders", "school", "sports", "travel", "unsplash", "wallpapers")"

**Comment by oobianom** [comment]
Look at the newest documentation now and see if it aligns with what you were thinking.

**Comment by brichard1638** [comment]
Suggested documentation revision supporting this function is provided as follows under the **Category Choices** section:

Remove the content, **"You may store all categories into a single vector 'imageCategories' for a cross-reference made available to the cat argument"**

...and replace with:

**Image categories can be captured in a separate vector as a cross-reference made available to the cat argument. For example:**

**imgcat= c("3D", "animals", "architecture", "backgrounds", "beauty", "experimental", "fashion", "film", "food", "interior", "nature", "people", "renders", "school", "sports", "travel", "unsplash", "wallpapers")**

**genRandImg(fp, cat = imgcat[9], n = 5)**

**Comment by oobianom** [comment]
Okay, great. This is now done and committed! Thanks for helping with the documentation.
